# Generated by Django 5.2.1 on 2025-05-08 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='etablissement',
            field=models.CharField(max_length=200),
        ),
    ]
